sender_ip: "127.0.0.1"
receiver_ip: "127.0.0.1"

port:
  data:
    source: 5300
    target: 5301

  acknowledgement:
    source: 5100
    target: 5101

window: 5
timeout: 1
file_name:
  sender: "../data/original.jpg"
  receiver: "../data/received.jpg"